CREATE TABLE TimeEntries (
    Location VARCHAR(255),
    LocationCode VARCHAR(255),
    Id BIGINT PRIMARY KEY,
    GUID CHAR(36),
    EmployeeId BIGINT,
    EmployeeGUID CHAR(36),
    EmployeeExternalId BIGINT,
    EmployeeName VARCHAR(255),
    JobId BIGINT,
    JobGUID CHAR(36),
    JobCode VARCHAR(255),
    JobTitle VARCHAR(255),
    InDate DATETIME,
    OutDate DATETIME,
    AutoClockOut BOOLEAN,
    TotalHours DECIMAL(5,2),
    UnpaidBreakTime DECIMAL(5,2),
    PaidBreakTime DECIMAL(5,2),
    PayableHours DECIMAL(5,2),
    CashTipsDeclared DECIMAL(10,2),
    NonCashTips DECIMAL(10,2),
    TotalGratuity DECIMAL(10,2),
    TotalTips DECIMAL(10,2),
    TipsWithheld DECIMAL(10,2),
    Wage DECIMAL(10,2),
    RegularHours DECIMAL(5,2),
    OvertimeHours DECIMAL(5,2),
    RegularPay DECIMAL(10,2),
    OvertimePay DECIMAL(10,2),
    TotalPay DECIMAL(10,2)
);
