-- Drop menus table
BEGIN;
TRUNCATE TABLE menus RESTART IDENTITY CASCADE;
DROP TABLE IF EXISTS menus;
COMMIT;

-- Drop time_entries table
BEGIN;
TRUNCATE TABLE time_entries RESTART IDENTITY CASCADE;
DROP TABLE IF EXISTS time_entries;
COMMIT;

-- Drop jobs table
BEGIN;
TRUNCATE TABLE jobs RESTART IDENTITY CASCADE;
DROP TABLE IF EXISTS jobs;
COMMIT;

-- Drop employees table
BEGIN;
TRUNCATE TABLE employees RESTART IDENTITY CASCADE;
DROP TABLE IF EXISTS employees;
COMMIT;

-- Drop locations table
BEGIN;
TRUNCATE TABLE locations RESTART IDENTITY CASCADE;
DROP TABLE IF EXISTS locations;
COMMIT;

